#!/usr/bin/env python
import httplib
import os
import sys

# TOKEN = 'Put token there'


def share_file(path, token):
    connection = httplib.HTTPSConnection('webdav.yandex.ru')
    connection.request('POST', ('%s?publish' % path), '', {
                       'Authorization': 'OAuth %s' % token
                       })
    response = connection.getresponse()
    if response.status == 302:
        return response.getheader('Location')
    else:
        raise EnvironmentError('Failed to share file: %s' % response.reason)

def unshare_file(path, token):
    connection = httplib.HTTPSConnection('webdav.yandex.ru')
    connection.request('POST', ('%s?unpublish' % path), '', {
                       'Authorization': 'OAuth %s' % token
                       })
    response = connection.getresponse()
    if response.status == 200:
        return True
    else:
        raise EnvironmentError('Failed to unshare file: %s' % response.reason)

def get_yad_path():
    os.system('df | grep webdav.yandex | awk \'{print $6}\' > /tmp/pyyad')
    return open('/tmp/pyyad').read()

def normalize_path(path):
    yad = get_yad_path().strip()
    if not path.startswith(yad):
        raise EnvironmentError('File %s is not under yadi.sk control!' % path)
    else:
        return path.split(yad)[1]

if __name__ == '__main__':
    path = None
    try:
        path = os.path.abspath(sys.argv[1])
        operation = sys.argv[2]
    except IndexError:
        if path:
            operation = 'share'
        else:
            path = os.getcwd()
            operation = 'status'

    if operation == 'share':
        try:
            link = share_file(normalize_path(path), TOKEN)
            os.system('echo "%s" | xclip -selection clipboard' % link)
        except EnvironmentError, e:
            print e
    elif operation == 'u':
        try:
            unshare_file(normalize_path(path), TOKEN)
        except EnvironmentError, e:
            print e
    elif operation == 'status':
        try:
            normalize_path(path)
            print 'This dir is under yadi.sk'
        except EnvironmentError, e:
            print 'This dir is not under yadi.sk'